### ISSUE TITLE
Incorrectly Labeled Section

### ISSUE THREAD

**Issue by JJFranko** [uswds/uswds-tutorial#11]
Going through the tutorial, under section 9 "Remove unnecessary styles" the documentation states 

> Let's open up the USWDS Sass entry point (_theme/styles.scss), uncomment the packages we need, and comment out the main uswds package.

However in the following section under the blue filename tag it shows "_theme/_uswds-theme.scss" instead of "_theme/styles.scss"

`<h4 class="filename"><span class="material-icons" aria-hidden="true">description</span> _theme/_uswds-theme.scss</h4>`

**Comment by mejiaj** [comment]
Closed in #7.
