### ISSUE TITLE
USWDS-Tutorial - Feature: Drupal and WP Versions

### ISSUE THREAD

**Issue by lagates** [uswds/uswds-tutorial#18]
### Is your feature request related to a problem? Please describe.

This tutorial is really great for getting your head around the new version 3 of the design system and the compile too. However, when it comes to a Drupal or Wordpress site and piping compiled sass is involved is where it becomes more of a challenge. 

### Describe the solution you'd like

Would be great for there to be a demo drupal and/or word press demo project that does the barebones setup and compile like with the static demo.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://designsystem.digital.gov/about/community/#community-conduct).
- [X] I checked the [current issues](https://github.com/uswds/uswds-tutorial/issues) for duplicate feature requests.

**Comment by thisisdano** [comment]
I think this is a good idea, but we will not be able to get to this on our current roadmap
